# Common defaults for all containers
x-default-container: &default-container
  environment:
    - PUID=1000
    - PGID=100
    - TZ=Africa/Harare
  restart: unless-stopped

# Extension for mediarr-related containers
x-mediarr-container: &mediarr-container
  <<: *default-container
  networks:
    - mediarr

services:
  bazarr:
    <<: *mediarr-container
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    hostname: bazarr
    volumes:
      - ./configs/mediarr/bazarr:/config
      - /b/Servarr/Media:/mnt/media
      - /b/Servarr/Downloads:/mnt/downloads
    ports:
      - 6767:6767
    depends_on:
      - sonarr
      - radarr

  jellyseerr:
    <<: *mediarr-container
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    hostname: jellyseerr
    ports:
      - 5055:5055
    volumes:
      - ./configs/mediarr/jellyseerr:/app/config
      - /b/Servarr/Media:/mnt/media
      - /b/Servarr/Downloads:/mnt/downloads
    depends_on:
      - sonarr
      - radarr

  prowlarr:
    <<: *mediarr-container
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    hostname: prowlarr
    volumes:
      - ./configs/mediarr/prowlarr:/config
      - /b/Servarr/Media:/mnt/media
      - /b/Servarr/Downloads:/mnt/downloads
    ports:
      - 9696:9696
    depends_on:
      - flaresolverr

  flaresolverr:
    <<: *mediarr-container
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    hostname: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    volumes:
      - flare_config:/config

  qbittorrent:
    <<: *mediarr-container
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    hostname: qbittorrent
    environment:
      - WEBUI_PORT=8080
    volumes:
      - ./configs/mediarr/qbittorrent:/config
      - /b/Servarr/Media:/mnt/media
      - /b/Servarr/Downloads:/mnt/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp

  radarr:
    <<: *mediarr-container
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    volumes:
      - ./configs/mediarr/radarr:/config
      - /b/Servarr/Media:/mnt/media
      - /b/Servarr/Downloads:/mnt/downloads
    ports:
      - 7878:7878
    depends_on:
      - prowlarr
      - qbittorrent

  sonarr:
    <<: *mediarr-container
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    volumes:
      - ./configs/mediarr/sonarr:/config
      - /b/Servarr/Media:/mnt/media
      - /b/Servarr/Downloads:/mnt/downloads
    ports:
      - 8989:8989
    depends_on:
      - prowlarr
      - qbittorrent

  homepage:
    <<: *mediarr-container
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    hostname: homepage
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=*
      - DOCKER_DISCOVERY=true
      - DOCKER_NETWORK=mediarr
    volumes:
      - ./configs/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 3000:3000

  caddy:
    <<: *default-container
    image: caddy:latest
    container_name: caddy
    # network_mode: host
    hostname: caddy
    env_file: .env.caddy.local
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./configs/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - mediarr
    depends_on:
      - homepage
      - sonarr
      - radarr
      - prowlarr
      - bazarr
      - qbittorrent
      - jellyseerr

networks:
  mediarr:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  flare_config:
